spring-boot-demo:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: true

  # 拦截器配置
  interceptor-config:
    resource-config:
      include-path: ${spring-boot-demo.resource-access-patterns}

  # 文件上传下载配置
  upload-path: /Users/Lucky/Code/demo/src/main/resources/upload/
  # 资源访问路径
  resource-access-path: /resource/
  # 资源访问路径匹配：/resource/**
  resource-access-patterns: ${spring-boot-demo.resource-access-path}**
  # 资源访问全路径前缀：http://localhost:8090/resource/
  resource-access-url: http://localhost:${server.port}${server.servlet.context-path}${spring-boot-demo.resource-access-path}



server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://47.112.96.185:3306/db_jd_shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: db_jd_shop
    password: Nmy5AZiYH5ei3zA7
  #  datasource:
  #    url: jdbc:oracle:thin:@192.168.43.204:1521:orcl
  #    username: spring_boot_plus
  #    password: Oracle111

  # Redis配置
  redis:
    database: 0
    host: localhost
#    password:
    port: 6379


# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    path: logs/spring-boot-demo.log

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
        db-config:
          logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
          logic-delete-value: 1 # 逻辑已删除值(默认为 1)
          logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)